# Generated by Django 6.0.2 on 2026-05-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0002_wikicategory_wikipage_wikilink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='world',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='world',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together={('world', 'title')},
        ),
    ]
