# Generated by Django 6.0.2 on 2026-05-03 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0003_rename_user_world_owner_alter_world_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('world', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loredb.world')),
            ],
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loredb.wiki'),
        ),
    ]
