# Generated by Django 6.0.2 on 2026-05-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='founder',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
