# Generated by Django 6.0.2 on 2026-05-06 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0006_location_founder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='character',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AddField(
            model_name='character',
            name='birthplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthplace_characters', to='loredb.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='deathplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deathplace_characters', to='loredb.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='characters',
            field=models.ManyToManyField(blank=True, to='loredb.character'),
        ),
        migrations.AddField(
            model_name='item',
            name='characters',
            field=models.ManyToManyField(blank=True, to='loredb.character'),
        ),
        migrations.AddField(
            model_name='item',
            name='locations',
            field=models.ManyToManyField(blank=True, to='loredb.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='characters',
            field=models.ManyToManyField(blank=True, to='loredb.character'),
        ),
        migrations.AddField(
            model_name='location',
            name='decline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='founding_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
