# Generated by Django 6.0.2 on 2026-05-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0007_remove_character_location_remove_item_character_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='family_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
