# Generated by Django 6.0.2 on 2026-05-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0008_character_family_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wikipage',
            old_name='world',
            new_name='wiki',
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together={('wiki', 'title')},
        ),
        migrations.AddField(
            model_name='wikicategory',
            name='wiki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loredb.wiki'),
        ),
        migrations.AlterUniqueTogether(
            name='wikicategory',
            unique_together={('wiki', 'name')},
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wiki',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wikicategory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wikilink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='world',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='wikicategory',
            name='world',
        ),
    ]
