# Generated by Django 6.0.2 on 2026-05-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0009_rename_world_wikipage_wiki_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loredb.world')),
            ],
        ),
    ]
