# Generated by Django 6.0.2 on 2026-05-13 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0010_race'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loredb.race'),
        ),
    ]
