# Generated by Django 6.0.2 on 2026-06-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0011_alter_character_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikipage',
            name='category',
        ),
        migrations.AddField(
            model_name='wikipage',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home Page'), ('normal', 'Normal Page'), ('category', 'Category Page')], default='normal', max_length=20),
        ),
    ]
