# Generated by Django 6.0.2 on 2026-06-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0013_categorypage_elementlesspage_homepage_normalpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categorized_pages', to='loredb.categorypage'),
        ),
    ]
