# Generated by Django 6.0.2 on 2026-06-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0014_wikipage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='page_type',
            field=models.CharField(choices=[('home', 'Home Page'), ('normal', 'Normal Page'), ('elementless', 'Elementless Page'), ('category', 'Category Page')], default='normal', max_length=20),
        ),
    ]
