# Generated by Django 6.0.2 on 2026-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0015_alter_wikipage_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='elementlesspage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='normalpage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
