# Generated by Django 6.0.2 on 2026-06-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0017_faction_group_collaborator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Object',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='can_delegate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaborator',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
