# Generated by Django 6.0.2 on 2026-06-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loredb', '0018_rename_item_object_collaborator_can_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='assigned_pages',
            field=models.ManyToManyField(blank=True, related_name='assigned_pages', to='loredb.wikipage'),
        ),
        migrations.AddField(
            model_name='normalpage',
            name='element_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalpage',
            name='element_type',
            field=models.CharField(choices=[('character', 'Character'), ('location', 'Location'), ('event', 'Event'), ('object', 'Object'), ('group', 'Group'), ('faction', 'Faction'), ('race', 'Race')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WikiLink',
        ),
    ]
